# ==========================
# ? ??????? ???? ???????
# ==========================
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options=-Xmx2048m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

# ==========================
# ? ??????? Kotlin Daemon
# ==========================
# ????? ???????????? ?????????? ????? ???? ????? ???????
kotlin.daemon.useFallbackStrategy=true
kotlin.compiler.execution.strategy=daemon
kotlin.incremental=true
kotlin.incremental.java=true
kotlin.code.style=official

# ==========================
# ? ??????? Android
# ==========================
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true

# ==========================
# ? ????? ?????? (???????)
# ==========================
org.gradle.workers.max=4
ksp.incremental=true
ksp.use.worker.api=true
ksp.allow.all.warning.messages=false
org.gradle.welcome=never
